---
author: Xingyu Zhong

format:
  html: default
---

# Preface {.unnumbered}

{{< include ../README.md >}}

{{< pagebreak  >}}

## Acknowledgements

The main motivation for this course is to promote Lean 4 and formalized mathematics to students majoring in mathematics at Beijing Institute of Technology, as well as to provide a structured exposition of Lean 4 and formalized mathematics with the author's personal flavor. Prior to this course, the author was first introduced to Lean and formal mathematics in the summer of 2024 via [an invited talk](https://math.bit.edu.cn/xsgz/xgdt/a5ac74f68b9840dba8dd700885a1d650.htm) by Jia Li (李嘉) on [Project Numina](https://projectnumina.ai/) at Beijing Institute of Technology. One year later, he had the chance to participate in the [2025 algebra and formalization summer school](https://mp.weixin.qq.com/s?__biz=MzkzOTE3NTU4Mw==&mid=2247511705&idx=1&sn=767e708e18f8e7eddd000ff9c507d65b) held in Renmin University of China and Beijing International Center for Mathematical Research. The author wishes to express gratitude to the organizers and participants of these events for the inspiring experience, especially Professor Riccardo Brasca for his wonderful lectures. The teaching style of this course was deeply inspired by [Kevin Buzzard's 2024 course on formalising mathematics in the Lean theorem prover](https://github.com/ImperialCollegeLondon/formalising-mathematics-2024). The author would like to thank Professor Yangyu Fan (范洋宇), for kindly allowing this hobby course to be offered alongside his *Abstract Algebra* course in Fall 2025 at Beijing Institute of Technology. The author is grateful to Junchao Huang (黄俊超), for providing the after-class exercises, and his valuable suggestions from his perspective as an AI4Math researcher. Finally, the author would like to thank all the fellow students who kindly scheduled their time to participate in this purely extra-curricular course. Yihan Zhuo (卓逸涵) deserve special thanks for his full attendance and active participation throughout the course.

```{=latex}
\vspace{2cm}

\begin{flushright}
```

Xingyu Zhong (钟星宇)  
<https://scholar.sun123zxy.top>

```{=latex}
\vspace{0.5cm}
```

December 2025, Beijing

```{=latex}
\end{flushright}
```